version: '3.9'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: usersDB
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_TCP_PORT: 3306
        container_name: mysql_users
        ports:
            - 3307:3306
        expose:
            - 3307
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - gateway_sharedNet

    adminer:
        image: adminer
        restart: always
        container_name: adminer_users
        ports:
            - 8081:8080
        expose:
            - 8082
        networks:
            - gateway_sharedNet

    app:
        build:
            context: ./
        container_name: users
        ports:
            - '3001:3001'
        environment:
            - DATABASE_URL=mysql://root:root@mysql_users:3306/usersDB
        volumes:
            - ./src:/app/src:z
        networks:
            - gateway_sharedNet
        depends_on:
            - db
        entrypoint: ['sh', '-c', 'npx prisma migrate deploy && npm run dev']

networks:
    gateway_sharedNet:
        external: true

volumes:
    db-data:
