version: '3.9'

services:
    app:
        build:
            context: ./
        container_name: gateway
        ports:
            - '3000:3000'
        entrypoint: ['sh', '-c', 'npm run dev']
        networks:
            - sharedNet

networks:
    sharedNet:
        driver: bridge
