version: '3.9'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: restaurantDB
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_TCP_PORT: 3306
        container_name: mysql_restaurants
        ports:
            - 3308:3306
        expose:
            - 3308
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - gateway_sharedNet

    adminer:
        image: adminer
        restart: always
        container_name: adminer_restaurants
        ports:
            - 8082:8080
        expose:
            - 8082
        networks:
            - gateway_sharedNet

    app:
        build:
            context: ./
        container_name: restaurants
        ports:
            - '3002:3002'
        environment:
            - DATABASE_URL=mysql://root:root@mysql_restaurants:3306/restaurantsDB
        volumes:
            - ./src:/app/src:z
        networks:
            - gateway_sharedNet
        depends_on:
            - db
        entrypoint: ['sh', '-c', 'npx prisma migrate deploy && npm run dev']

networks:
    gateway_sharedNet:
        external: true

volumes:
    db-data:
